README.md
base-template.sh
cli.sh
install.sh

Install into existing repos should be able to be skipped.
I need this because I want to configure this install skript for an auto install procedure.

Optional skipping install into existing repos.

---

README.md
base-template.sh
cli.sh
docs/command-line-tool.md
examples/tools/dialog/run
install.sh
tests/coverage.sh
tests/exec-tests.sh
tests/step-032.sh
tests/step-042.sh
tests/step-076.sh
tests/step-077.sh
tests/step-104.sh

Another try. Fixed the `read -r VARIABLE`

Dispatch user prompts to dialog tool. :heart:

---

base-template.sh
cli.sh
install.sh
tests/exec-steps.sh

I searched for all `find` statements and found some which do not work with 
whitespaces in path names, I corrected them.
Thanks for reviewing this.

Whitespaces in paths break for loop

---

.travis.yml
base-template.sh
cli.sh
install.sh
tests/exec-tests.sh
tests/step-016.sh
tests/step-039.sh
tests/step-040.sh
tests/step-041.sh
tests/step-067.sh
tests/step-105.sh
tests/step-106.sh
tests/step-107.sh
tests/test-alpine-lfs.sh

This is my attempt to solve #17 
@gabyx @AlexGoris-Cashforce can you please have a look?

Support for running Git LFS hooks :green_heart:

---

appveyor.yml
tests/test-windows.sh

Trying to make an appveyor test.
@rycus86 Could you enable appveyor for this repo, to be able to test this?

Windows tests. :yellow_heart:

---

base-template.sh
cli.sh
install.sh

The check should be like the one provided. Thx for merging.

Small Bugfix. Shared Repos missing.

---

base-template.sh
cli.sh
install.sh

Prompts needed a little fix. Incldue whole message otherwise the context is unknown for the user in GUI mode... Thx for merging this.

Include whole message in prompt to have context.

---

examples/tools/download/run

Small example fix.

---

README.md
base-template.sh
cli.sh
install.sh
tests/exec-steps.sh
tests/step-108.sh
uninstall.sh

Customized install prefix

---

base-template.sh
cli.sh
docs/command-line-tool.md
install.sh
uninstall.sh

Uninstalling and Git LFS

---

base-template.sh
cli.sh
install.sh

Small bugfix for show_prompt. Arguments are now parsed correct.
Thx for merging :-)

Missing hint text in prompt :tada:

---

base-template.sh
cli.sh
install.sh
tests/step-106.sh

This is an urgent bugfix :-). to #51 
Thanks for squash merging.

Bugfix: lfs hooks should always run

---

uninstall.sh

Samll LFS fix. Wrong variable in Reinstall. Thx for merging

Bugfix: Wrong variable in LFS reinstall.

---

README.md

Remove experimental for download/dialog tool

---

README.md
base-template.sh
cli.sh
install.sh
tests/step-109.sh
tests/step-110.sh
uninstall.sh

Some initial fixes to allow bare repo installs.
Tests should be added...
@rycus86 Could you do this?

Install into bare repos.

---

base-template.sh
cli.sh
docs/command-line-tool.md
install.sh
tests/exec-tests.sh
tests/step-111.sh
uninstall.sh

Feature: Delete detected LFS Hooks

---

README.md
base-template.sh
cli.sh
install.sh
tests/step-109.sh
uninstall.sh

Feature: Maintain only server hooks :heart:

---

base-template.sh
cli.sh
install.sh

Dito
Why does it need the `-E` ?

Fix test 111 

---

base-template.sh
cli.sh
install.sh
tests/exec-tests.sh
tests/step-116.sh
tests/test-windows.sh
uninstall.sh

**Criticall fix. The test should work now.**
https://travis-ci.org/rycus86/githooks/builds/644352092
Except coverage which needs fixing later...
Made some stupid error. As you said, there was still a place where I forgot to check the correct git-dir.
Changed also stupid variable names `GIT_DIR` to `REPO_GIT_DIR`.
Sorry for the mistakes...

Critical Bugfix: Correct wrong git-dir in install.

---

base-template.sh
cli.sh
install.sh
tests/step-109.sh
tests/step-110.sh
tests/step-116.sh
uninstall.sh

Better implementation as suggested from #85. 
The prompt needs to be shown because of the tests and I would leave it like this...

Test if /dev/tty can be opened before reading it 

---

base-template.sh
cli.sh
install.sh

Small CLI fix:
Function `run_update_check` -> `read_single_repo_info` might be executed  while not in a repository, outputting an error.

Bugfix: guard run_update_check

---

base-template.sh
cli.sh
install.sh
uninstall.sh

Smal difference fix in duplicated implementation.

---

base-template.sh
cli.sh
install.sh

Logic after read is potentially harmful.
Small refactor.
Thx for mergin.

Small refactor: logic after read wrong :zap:

---

base-template.sh
cli.sh
install.sh

- whitespace problem
Thx for merging

Bugfix: Quote hook alias :boom:

---

base-template.sh
cli.sh
install.sh
tests/test-whitespace.sh

Add whitespace to user folder -> fails some new tests
Second commit fix all tests -> IFS problems...
Thx for merging

Bugfix: whitespace problems in home folder

---

.githooks/pre-commit/has-shell-function-comments
base-template.sh
cli.sh
install.sh
tests/step-097.sh
tests/step-098.sh
tests/test-rules.sh

Fix the tests/test-rule.sh
- new shfmt version
and
- new shellcheck version

1: Fix rules test :star:

---

docs/command-line-tool.md

Just documentation which is obsoltet. Thx for mergin.

[doc] Remove old non existent commands

---

base-template.sh
cli.sh
install.sh

- small refactor for better understanding
- outsource warning and checks into check_deprecation
- explicit return values
Thanks for mergin

1: Bugfix: Show deprecation warning only once

---

base-template.sh
cli.sh
install.sh

Stupid typo :
Merge please 
:-| 
thx.

Bugfix: Stupid typo

---

cli.sh
uninstall.sh

Some small refactoring and dispatch to `uninstall.sh`
and deleting of old `$INSTALL_DIR/autoupdate` folder...

Bugfix: uninstall from clone

---

cli.sh

Also prompt the user what he wants to do, default is no recloning

Bugfix: Error if update clone is wrong configured

---

install.sh

Typo :zap:

---

.githooks/pre-commit/no-set-x
install.sh
uninstall.sh

- commit  10feafbd56a86296985b104
- PullRequest 104

Revert: cli.sh use from release folder

---

install.sh

Do not execute legacy_transform_end on single (this repo only) install 

---

install.sh

- in the update case, we need to include a set `githooks.useCoreHooksPath` and warn and fail if we did not find a template directory after checking the default locations.
Thanks for merging.
Maybe later an additional update in 114. But not much time now.

Correctly detect hook template directory

---

cli.sh

Bugfix: No output if not in local repo

---

install.sh

Bugfix: Fix weird output

---

install.sh

Another one. Thanks for mergin.

Bugfix: Remove weird output

---

install.sh

Another subtle one :-)
Checked all other `rev-parse` invocations, they seem fine. 🤞 
Thanks for merging.

Bugfix: wrong rev-parse checks

---

base-template.sh

Small fix for `file://` which takes the wrong path here.

Bugfix: Fix wrong output for local urls.

---

install.sh

Bugfix: Fix output and make legacy transform more agnostic

---

base-template.sh

Redirect also the output of install.sh in base-template.sh

---

.githooks/.ignore
.githooks/commit-msg/add-random-emoji
.githooks/pre-commit/.export-staged
.githooks/pre-commit/no-set-x
.githooks/pre-commit/no-tabs
.githooks/pre-commit/no-todo-or-fixme
.githooks/pre-commit/shellcheck
.githooks/pre-commit/shellcheck-ignore-format
.githooks/pre-commit/shfmt

A cherry-pick from currenty go-refactoring.
Makes these hooks way faster. I more and more god fed up that it takes too long ;-)
Tested them, works.

Faster repository hooks :purple_heart:
