README.md
base-template.sh
cli.sh
install.sh

As requested this has been separated from #19 .
I've added a custom template directory to the install script.
By passing `--template-dir` to the install script, the user can specify
which directory should be used for the teomplate directory
Also, when `--non-interactive` is passed (regardless of the above!) the script will continue with setting a new template directory if it can't find a pre-existing one, either to the directory specified by the user, or to a default directory.

Let the install script continue when --non-interactive is passed and no pre-existing template directory is found

---

README.md
base-template.sh
cli.sh
docs/command-line-tool.md
examples/tools/dialog/run
install.sh
tests/exec-tests.sh
tests/step-032.sh
tests/step-042.sh
tests/step-076.sh
tests/step-077.sh

Introduce a small tool "dialog" which dispatches all dialog prompts in `base-template.sh` to a script.
An example implementation with python3.6 and higher is given in `examples/tools/dialog`.

Dispatch User Prompts to Dialog Tool

---

.githooks/pre-commit/auto-update-inline-content
base-template.sh
cli.sh
install.sh
tests/step-103.sh
uninstall.sh

The `step-103.sh` should be failing. I wrote it because it does not in my setup.
-> Installing shared hooks and then accidentially removing them and making a commit should fail because the hooks are not there.
Solution: Do an update if the hooks are not there, or fail with an error "run git hooks shared update"

Bugfix: Fail on not available shared hook.

---

README.md
base-template.sh
cli.sh
install.sh
tests/test-corehookspath.sh
uninstall.sh

We noticed this project (thanks!) and wanted to use it within our organization, however to make it better suited to use in our teams, we made 2 changes:
* When running script with the `--non-interactive` parameter, the script now continues to setup a new template directory if it can't find an existing one (which is the case in most default git installations)
* The script can now be installed with `--use-hookspath` parameter, in which case the script will make the template directory the directory configured as the `core.hooksPath` parameter in the global git configuration. This allows for easier application to existing repositories, avoiding the need to search the entire disk for existing repositories.
I've updated the `README.md` for the 2nd point, to try to instruct users which mode …

Add installation via core.hooksPath and setup new templatedir when running in non-interactive mode

---

base-template.sh
cli.sh
install.sh

Some small bugfix. Thx for merging.
This will work for sure on UNIX. 
```shell
rm -f "$TARGET_HOOK" >/dev/null 2>&1
```
On Windows it might not (cannot delete open files...) resulting in the same behavior which did not make problems so far on windows.

Bugfix: Dont overwrite running hooks.

---

base-template.sh
cli.sh
install.sh

Can we revert this. I hope this fix instead of `env -i` also passes all tests.
Also we forgot to put `-c core.hooksPath=/dev/null` as you mentioned. Which is necessary.
Why this revert: `env -i` kills everything including credentials somehow, so you need to enter passwords again etc....

Bugfix: env -i is to restrictive

---

README.md
base-template.sh
cli.sh
install.sh
tests/step-113.sh
tests/step-114.sh

Related to #67 
I believe this was just a documentation mistake.
We don't really want to create directories anywhere, so we get implicit consent from the user by:
- getting the path they want from `--template-dir`, and
- requiring that the target template directory exists that we've been given
This PR fixes the README, and adds two tests to show the install script invocation.

Template dir fixes :green_heart:

---

base-template.sh
cli.sh
install.sh

Can we change that? 
`git hooks shared update` fails with `env: ‘git’: No such file or directory`
on windows. The reason for this change to `env -i` was because of defined `GIT_DIR` and stuff...
I changed it to a less harsh method. I also added to ignore running any hooks.
Thanks for merging. Hopefully all tests still work with that.

Bugfix: env -i is too restrictive. 

---

base-template.sh
cli.sh
install.sh

This is a bugfix when githooks is disabled. In my opinion, the following changes should happen.

Bugfix: Execute old hooks also when disabled.

---

base-template.sh
cli.sh
install.sh
tests/step-116.sh
tests/test-whitespace.sh
uninstall.sh

No changes had to be made to any tests. They all work.
This is the PR for the monologue in #55. 
We improved the following:
- All repos which use Githooks hooks are now registered for autoupdates (if not single install) in `~/.gihooks/autoupdate/registered` in all circumstances, that means
- `git init` -> first use of any hook -> registers this repo
- `git hooks install` in repo -> register directly over `install.sh`
- `git hooks update` in repo -> dito because of `install.sh`
- running any Githook hook -> registering if not done (cheap)
- running manually `install.sh` -> registering directly for any install happening...
An install triggered by a running hook now calls `DO_ONLY_UPDATE="yes" install.sh` meaning
- if called in a single install repo, we update ony this repo.
- in any other …

Register repos for auto update.

---

base-template.sh
cli.sh
install.sh
uninstall.sh

To review. Not yet perfect.
```
GIT_DIR=$(cd "$EXISTING" && GIT_DISCOVERY_ACROSS_FILESYSTEM=0 git rev-parse --git-dir)
```
needs revisit. Return relative path??

Bugfix: Finding git directories.

---

base-template.sh
cli.sh
install.sh

Hooks execution on the server results in:
This small fix, fallsback to `stdin` if `dev/tty` is not allocated, which is the case when running the hook on the server.

Don't show fallback prompt if /dev/tty is not available.

---

base-template.sh
cli.sh
install.sh

By https://github.com/rycus86/githooks/pull/81#issuecomment-614782632
this fix should fix the logic when we read from /dev/tty for getting an answer to a prompt.
We dont modify the variable read into if we could not read something from a controlling terminal:
@matthijskooijman Shouldn't we only (if and only if) read from /dev/tty when stdin is also a tty meaning the change should be maybe even more strict: 
```shell
if [-t 0] && [ -t 1 ]; then
printf "%s %s [%s]:" "$TEXT" "$HINT_TEXT" "$SHORT_OPTIONS"
read -r "$VARIABLE" </dev/tty
fi
```

Bugfix: No prompt if no controlling terminal could be detected :tada:

---

base-template.sh
cli.sh
install.sh

Small bugfix for master.
Same problem we had already: Forgotten to really safely execute git commands in the clone dir.
Windows problems so far I think.
PR #93 and continuation will have some improvements on that too... but not important for this bugfix.

Safely execute git commands :zap:

---

base-template.sh
cli.sh
install.sh

Szenenario: Fresh install
- set a (init.templateDir)  e.g `~/mytemplates`
- install fails with (`Git hook templates directory not found`) because mkdir is at the wrong place. 
See small Bugfix. 
Thanks for merging.

Bugfix: Create template directory in all cases :tada:

---

.travis.yml
README.md
base-template.sh
cli.sh
docs/command-line-tool.md
install.sh
tests/step-039.sh
tests/step-042.sh
tests/step-103.sh
tests/step-109.sh

Only a warning, to let user know that single installs are deprecated with further installs.
No changes to any logic. Documentation marks all places as deprecated.

Deprecation warning added for single installs

---

base-template.sh
cli.sh
install.sh
tests/exec-steps.sh
tests/step-038.sh
tests/step-094.sh
uninstall.sh

A **small** refactor to move global git config variables to make them more consistent.
githooks.autoupdate.updateCloneUrl -> githooks.cloneUrl
githooks.autoupdate.updateCloneBranch -> githooks.cloneBranch
githooks.previous.searchDir -> githooks.previousSearchDir
See `legacy_transformation` in `install.sh` which takes care of transformation and deleting old values.
Thanks for merging =)

1: Refactor: Make githooks config variables more consistent :tada:

---

.githooks/pre-commit/no-set-x
README.md
base-template.sh
cli.sh
docs/command-line-tool.md
install.sh
tests/coverage.sh
tests/exec-steps.sh
tests/exec-tests.sh
tests/step-005.sh
tests/step-016.sh
tests/step-018.sh
tests/step-023.sh
tests/step-024.sh
tests/step-061.sh
tests/step-082.sh
tests/step-083.sh
tests/step-084.sh
tests/step-092.sh
tests/step-103.sh
tests/step-110.sh
tests/step-112.sh
tests/step-115.sh
tests/step-117.sh
tests/step-119.sh
tests/test-debian.sh
tests/test-opensuse.sh
tests/test-ubuntu.sh
tests/test-windows.sh
uninstall.sh

Based on discussion in #122. Based on #119.

Refactor shared hooks settings

---

README.md
base-template.sh
install.sh
uninstall.sh

This is a PR to trigger shared hooks update by a global or local `githooks.sharedHooksUpdateTriggers` setting, which is a comma separated list (does not matter we just grep for the name) of hook names which all trigger the shared hook update additional to `post-merge` and `post-checkout 00000...`
This is related to #123 
@rycus86 : What do you think?
- ~[ ] Maybe needs a cli implementation (I think its not so important)~

Added global setting to trigger shared update by custom hook names

---

install.sh
tests/step-120.sh

This needs fixes. See test 120.sh which should not fail.
I add the fixes to this PR.

Bugfix: wrong --use-core-hookspath logic

---

install.sh

Thanks for merging.
We should pass a null ref to `--internal-updated-from` such that we know we have newly cloned the release clone.
Might come handy in the future.
Furthermore related to this problem and a bit trickier:
- I installed with a local path as the clone url -> `/data/git/repositories/githooks.git`  (on a gitea server)
- This results in a stupid `legacy_transform_after_update` because `--depth 1` is not honoured for local paths (git stuff)  and the  `if [ "$COMMIT_COUNT" != "1" ]` passes... :bomb: 
This fix resolves this problem!

Bugfix: Pass zero ref to --internal-updated-from on clone

---

install.sh

- it has three destinct meanings:
- sha -> update commit from
- null sha -> new clone happened
- empty -> no update happened, still on the same sha
This is needed for the legacy check `[ -z "$INTERNAL_UPDATED_FROM_COMMIT" ]` in
legacy_transform_after_update,
which should only opt-in from old installs.
We forgot to make `--internal-update-from` bomb proof: This should hopefully fix
this.

Bugfix: Always setting the internal update flag is wanted

---

install.sh

- check variable to be unset
Thx for merging. Small stupid logic error :-)

Bugfix: Fix wrong legacy check

---

install.sh

Small fix because of either odd situation (just gracefully fixing this)
```
install.sh --clone-url "$url" \
--clone-branch "$branch"
```
and an allraedy installed githooks with release clone the same as "$url" and "$branch" but deleted configs `githooks.cloneUrl` etc...

Also set clone url after fetch
